# Generated by Django 4.2.1 on 2024-04-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
