# Generated by Django 5.0.2 on 2024-04-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0002_psychologist_consultation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
