# Generated by Django 5.0.2 on 2024-04-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0003_psychologist_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('document', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('history', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
